jp_instagram_home:
    pattern:  /
    defaults: { _controller: JPInstagramBundle:Home:index }

jp_instagram_user:
    pattern:  /user
    defaults: { _controller: JPInstagramBundle:User:index }

jp_instagram_tag:
    pattern:  /tag
    defaults: { _controller: JPInstagramBundle:Tag:index }
