jp_instagram_home:
    pattern:  /
    defaults: { _controller: JPInstagramBundle:Home:index }

jp_instagram_user:
    pattern:  /user
    defaults: { _controller: JPInstagramBundle:User:feed }

test1:
    pattern:  /test1
    defaults: { _controller: JPInstagramBundle:Home:test1 }

test2:
    pattern:  /test2
    defaults: { _controller: JPInstagramBundle:Home:test2 }