services:
    curl_manager:
        class: JP\InstagramBundle\Manager\CurlManager

    instagram_api_manager:
        class: JP\InstagramBundle\Manager\InstagramAPIManager
        arguments: [%instagram_base_endpoint%, %instagram_client_id%, %instagram_client_secret%, %instagram_tag%, %instagram_redirect_uri%, %instagram_access_token_url%, %instagram_authorization_url%, @curl_manager]
