jp_user:
    resource: "@JPUserBundle/Resources/config/routing.yml"
    prefix:   /

jp_ember_js:
    resource: "@JPEmberJSBundle/Resources/config/routing.yml"
    prefix:   /gta

jp_librato:
    resource: "@JPLibratoBundle/Resources/config/routing.yml"
    prefix:   /librato