jp_user:
    resource: "@JPUserBundle/Resources/config/routing.yml"
    prefix:   /user

jp_ember_js:
    resource: "@JPEmberJSBundle/Resources/config/routing.yml"
    prefix:   /gta

jp_librato:
    resource: "@JPLibratoBundle/Resources/config/routing.yml"
    prefix:   /librato

jp_instagram:
    resource: "@JPInstagramBundle/Resources/config/routing.yml"
    prefix:   /instagram

jp_misc:
    resource: "@JPMiscBundle/Resources/config/routing.yml"
    prefix:   /misc

jp_options_resolver:
    resource: "@JPOptionsResolverBundle/Resources/config/routing.yml"
    prefix:   /resolver
