jp_librato_home:
    pattern:  /site/home
    defaults: { _controller: JPLibratoBundle:Site:home }

jp_librato_homed:
    pattern:  /site/homed
    defaults: { _controller: JPLibratoBundle:Site:homed }

jp_librato_cart:
    pattern:  /site/cart
    defaults: { _controller: JPLibratoBundle:Site:cart }

jp_librato_order:
    pattern:  /site/order
    defaults: { _controller: JPLibratoBundle:Site:order }

jp_librato_post:
    pattern:  /site/post/{name}/{value}
    defaults: { _controller: JPLibratoBundle:Site:post }

jp_librato_statsd:
    pattern:  /site/statsd/{name}
    defaults: { _controller: JPLibratoBundle:Site:statsd }

jp_librato_annotation:
    pattern:  /site/annotation/{title}
    defaults: { _controller: JPLibratoBundle:Site:annotation }