services:
    jpc.dice:
        class: JP\DiceBundle\Dice\Dice
        abstract: true
        public : false

    jpc.dice.manager:
        class: JP\DiceBundle\Manager\DiceManager
        abstract: true;
        arguments: [null]